#!/usr/bin/env python3
# Copyright 2025 Ira Cooper <ira@wakeful.net>
# SPDX-License-Identifier: GPL-2.0-or-later

"""
Compress viable.json to LZMA and generate C header for embedding in firmware.
"""

import sys
import os
import lzma
import json

def compress_definition(json_path, output_path):
    """Compress JSON file and generate C header."""

    # Read and minify JSON
    with open(json_path, 'r') as f:
        data = json.load(f)

    # Minify (remove whitespace)
    json_str = json.dumps(data, separators=(',', ':'))
    json_bytes = json_str.encode('utf-8')

    # Compress with LZMA
    compressed = lzma.compress(
        json_bytes,
        format=lzma.FORMAT_ALONE,
        preset=9
    )

    # Generate C header
    with open(output_path, 'w') as f:
        f.write("// Auto-generated by viable_compress.py - DO NOT EDIT\n")
        f.write("// Copyright 2025 Ira Cooper <ira@wakeful.net>\n")
        f.write("// SPDX-License-Identifier: GPL-2.0-or-later\n\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n")
        f.write("#include \"progmem.h\"\n\n")
        f.write(f"#define VIABLE_DEFINITION_SIZE {len(compressed)}\n")
        f.write(f"#define VIABLE_DEFINITION_UNCOMPRESSED_SIZE {len(json_bytes)}\n\n")
        f.write("static const uint8_t PROGMEM viable_definition_data[] = {\n")

        # Write bytes in rows of 16
        for i in range(0, len(compressed), 16):
            chunk = compressed[i:i+16]
            hex_bytes = ', '.join(f'0x{b:02x}' for b in chunk)
            f.write(f"    {hex_bytes},\n")

        f.write("};\n")

    print(f"Compressed {json_path}: {len(json_bytes)} -> {len(compressed)} bytes ({100*len(compressed)//len(json_bytes)}%)")
    return True

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <viable.json> <output.h>")
        sys.exit(1)

    json_path = sys.argv[1]
    output_path = sys.argv[2]

    if not os.path.exists(json_path):
        # No viable.json - generate empty definition
        with open(output_path, 'w') as f:
            f.write("// Auto-generated - no viable.json found\n")
            f.write("#pragma once\n\n")
            f.write("#include <stdint.h>\n")
            f.write("#include \"progmem.h\"\n\n")
            f.write("#define VIABLE_DEFINITION_SIZE 0\n")
            f.write("#define VIABLE_DEFINITION_UNCOMPRESSED_SIZE 0\n\n")
            f.write("static const uint8_t PROGMEM viable_definition_data[] = {};\n")
        print(f"No viable.json found at {json_path}, generated empty definition")
        sys.exit(0)

    if not compress_definition(json_path, output_path):
        sys.exit(1)

if __name__ == '__main__':
    main()
