#!/usr/bin/env python3
# Copyright 2025 Ira Cooper <ira@wakeful.net>
# SPDX-License-Identifier: GPL-2.0-or-later

"""
Generate viable_config.h from viable.json.

Reads the 'viable' object from viable.json and generates C #defines
for each feature's entry count and enable flag.

Features not present in the JSON will not have defines generated,
allowing code to be excluded via #ifdef at compile time.
"""

import sys
import os
import json

# Map JSON keys to C define names
FEATURE_MAP = {
    'tap_dance': 'TAP_DANCE',
    'combo': 'COMBO',
    'key_override': 'KEY_OVERRIDE',
    'alt_repeat_key': 'ALT_REPEAT_KEY',
    'leader': 'LEADER',
}

# Map features to QMK enable flags (for rules.mk output)
QMK_ENABLE_MAP = {
    'tap_dance': 'TAP_DANCE_ENABLE',
    'combo': 'COMBO_ENABLE',
    'key_override': 'KEY_OVERRIDE_ENABLE',
    'leader': 'LEADER_ENABLE',
}


def generate_config(json_path, header_path, mk_path=None):
    """Generate viable_config.h from viable.json."""

    # Read JSON
    with open(json_path, 'r') as f:
        data = json.load(f)

    viable = data.get('viable', {})

    # Generate C header
    with open(header_path, 'w') as f:
        f.write("// Auto-generated by viable_config.py - DO NOT EDIT\n")
        f.write("// Copyright 2025 Ira Cooper <ira@wakeful.net>\n")
        f.write("// SPDX-License-Identifier: GPL-2.0-or-later\n\n")
        f.write("#pragma once\n\n")

        if not viable:
            f.write("// No viable configuration found in viable.json\n")
        else:
            for json_key, c_name in FEATURE_MAP.items():
                if json_key in viable:
                    count = viable[json_key]
                    f.write(f"#define VIABLE_{c_name}_ENTRIES {count}\n")
                    f.write(f"#define VIABLE_{c_name}_ENABLE 1\n\n")

    # Generate make fragment if requested
    if mk_path:
        with open(mk_path, 'w') as f:
            f.write("# Auto-generated by viable_config.py - DO NOT EDIT\n\n")
            for json_key, qmk_flag in QMK_ENABLE_MAP.items():
                if json_key in viable:
                    f.write(f"{qmk_flag} = yes\n")

    features = [k for k in FEATURE_MAP.keys() if k in viable]
    print(f"Generated viable config with features: {', '.join(features) if features else 'none'}")
    return True


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <viable.json> <output.h> [output.mk]")
        sys.exit(1)

    json_path = sys.argv[1]
    header_path = sys.argv[2]
    mk_path = sys.argv[3] if len(sys.argv) > 3 else None

    if not os.path.exists(json_path):
        # No viable.json - generate empty config
        with open(header_path, 'w') as f:
            f.write("// Auto-generated - no viable.json found\n")
            f.write("#pragma once\n\n")
            f.write("// No viable features enabled\n")
        if mk_path:
            with open(mk_path, 'w') as f:
                f.write("# Auto-generated - no viable.json found\n")
        print(f"No viable.json found at {json_path}, generated empty config")
        sys.exit(0)

    if not generate_config(json_path, header_path, mk_path):
        sys.exit(1)


if __name__ == '__main__':
    main()
